name: Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up vim
        uses: rhysd/action-setup-vim@v1
      - name: Install dotvim
        run: |
          git clone --recurse-submodules git://github.com/LKI/dotvim.git ~/.vim
          ln -sf ~/.vim/vimrc ~/.vimrc
          vim +PlugInstall +qall
      - name: Verification
        run: vim -c quit
