name: Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up vim
        uses: rhysd/action-setup-vim@v1
      - name: Install dotvim
        run: curl -s https://raw.githubusercontent.com/LKI/dotvim/master/install.sh | sh
      - name: Verification
        run: vim -c quit
